-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.publicaciones
(
    id serial NOT NULL,
    imagen_url text COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    fecha_publicacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fuente text COLLATE pg_catalog."default",
    titulo text COLLATE pg_catalog."default",
    tipo character varying(20) COLLATE pg_catalog."default" DEFAULT 'secundaria'::character varying,
    CONSTRAINT publicaciones_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.publicaciones_vistas
(
    id serial NOT NULL,
    visitante_id text COLLATE pg_catalog."default",
    publicacion_id integer,
    fecha_vista timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT publicaciones_vistas_pkey PRIMARY KEY (id),
    CONSTRAINT publicaciones_vistas_visitante_id_publicacion_id_key UNIQUE (visitante_id, publicacion_id)
);

CREATE TABLE IF NOT EXISTS public.resultados_test
(
    id serial NOT NULL,
    visitante_id text COLLATE pg_catalog."default" NOT NULL,
    carrera character varying(100) COLLATE pg_catalog."default" NOT NULL,
    puntaje integer NOT NULL,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT resultados_test_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.publicaciones_vistas
    ADD CONSTRAINT publicaciones_vistas_publicacion_id_fkey FOREIGN KEY (publicacion_id)
    REFERENCES public.publicaciones (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;